### ISSUE TITLE
How to use this light field rendering plugin in command line

### ISSUE THREAD

**Issue by Shzhuoyu** [IDLabMedia/blender-lightfield-addon#2]
I have a linux server, but no gui, so I'm wondering if it's possible to use the command line for lightfield rendering.

**Comment by mcourteaux** [comment]
I have struggled with the same problem. In the past I have overcome this with https://en.wikipedia.org/wiki/Xvfb. I ran Blender with this virtual X framebuffer as the `DISPLAY` environment variable. Then you could connect to it from a workstation. I don't know if Blender supports headless rendering. Probably it does, but never looked into it more.

**Comment by Shzhuoyu** [comment]
thank you!
