### ISSUE TITLE
OSError: read-only file system while enabling the addon

### ISSUE THREAD

**Issue by thomas0329** [IDLabMedia/blender-lightfield-addon#4]
I cloned the repo into the Blender addon directory, and when I clicked the checkbox to enable "6D Lightfield Renderer", I got this error
<img width="652" alt="Screenshot 2023-04-10 at 4 27 00 PM" src="https://user-images.githubusercontent.com/64268073/230867687-956241ca-290d-4d36-8c01-0d06f31248cb.png">

I tried setting writable permission to the blender-lightfield-addon folder with 
chmod -R 777 path/to/blender-lightfield-addon
but it didn't work.
If anyone happening to read this can help me out, I'd appreciate it greatly

**Comment by mcourteaux** [comment]
Looking into it. Will report back soon.

**Comment by mcourteaux** [comment]
Looking at the code, it makes a directory, which I think I don't like (I didn't write that bit), in the temporary folder configured in Blender itself:

    bpy.context.preferences.filepaths.temporary_directory

So, I'm guessing this temporary_directory is not configured at all, and is actually empty. Online, I find a screenshot:
![](https://devtalk.blender.org/uploads/default/optimized/2X/8/8fbe9eaf0d5cc5d70f0fa6fcba29c09dc6285494_2_602x500.png)

Please check if the "Temporary Files" field is filled out.

**Comment by mcourteaux** [comment]
This is definitely not to my liking that it immediately creates a new folder upon enabling the addon. I'll leave this on.

**Comment by mcourteaux** [comment]
I got rid of the automatic directory creation in the last commit, which you can also try.

**Comment by thomas0329** [comment]
> Looking at the code, it makes a directory, which I think I don't like (I didn't write that bit), in the temporary folder configured in Blender itself:
> 
> ```
> bpy.context.preferences.filepaths.temporary_directory
> ```
> 
> So, I'm guessing this temporary_directory is not configured at all, and is actually empty. Online, I find a screenshot: ![](https://camo.githubusercontent.com/38ee5090daf61682d6a62f48b3ea458d7c00efb5e7dbab9a4022f24e0b4fad42/68747470733a2f2f64657674616c6b2e626c656e6465722e6f72672f75706c6f6164732f64656661756c742f6f7074696d697a65642f32582f382f386662653965616630643563633564373066306661366663626132396330396463363238353439345f325f363032783530302e706e67)
> 
> Please check if the "Temporary Files" field is filled out.

That's the case. Sorry I'm new to blender. Thank you for your help!
